name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Pipeline executado com sucesso
        run: echo "CI configurado corretamente"
